//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int Material_ID { get; set; }
        public string Material_Name { get; set; }
        public decimal Material_Cost { get; set; }
    }
}
