//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibraryDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sklad_ZhikharevEntities : DbContext
    {

        private static Sklad_ZhikharevEntities _context;
        public Sklad_ZhikharevEntities()
            : base("name=Sklad_ZhikharevEntities")
        {
        }

        public static Sklad_ZhikharevEntities GetContext()
        {

            if (_context == null) _context = new Sklad_ZhikharevEntities();
            return _context;

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Materials> Materials { get; set; }
    }
}
